version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - network-hw
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    networks:
      - network-hw
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  network-hw:
    driver: bridge

volumes:
  db_data:
